spring:
    application:
        name: springboot
    batch:
        jdbc:
            initialize-schema: always

    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:         