spring.application.name=springboot

spring.security.user.name=admin
spring.security.user.password=$2a$10$h3rVNHrU4dx6V4py1cgPfu4AGLt6n14jPsisAqQ5rg.lYUThb0FhG

# h2 config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=