package com.sandbox.springboot.service;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import javax.crypto.SecretKey;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jws;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;

@Service
public class JwtService {
    
    @Value("${jwt.secret-key}")
    private String secret;

    @Value("${jwt.expiration-in-millis}")
    private long jwtExpirationInMillis;

    public String generateToken(String username) {
        SecretKey key = Keys.hmacShaKeyFor(this.secret.getBytes());
        Map<String, String> claims = new HashMap<>();
        claims.put("email", username + "@mail.com");
        
        return Jwts.builder()
            .claims(claims)
            .claim("role", "ADMIN")
            .subject(username)
            .issuedAt(new Date(System.currentTimeMillis()))
            .expiration(new Date(System.currentTimeMillis() + jwtExpirationInMillis))
            // .encryptWith(key, (AeadAlgorithm) Jwts.SIG.HS256) // without using encryption the tokens content can be viewed by anyone
            .signWith(key) // this is required to be able to verify that the token is generated by the server
            .compact();
    }

    public Jws<Claims> validateToken(String token) {
        SecretKey key = Keys.hmacShaKeyFor(this.secret.getBytes());
        try {
            return Jwts.parser()
                .verifyWith(key) // this is needed if signWith is used
                .build()
                .parseSignedClaims(token);
        } catch (Exception e) {
            System.out.println("Token validation failed: " + e.getMessage());
            return null;
        }
    }

    public boolean isTokenValid(String token) {
        return validateToken(token) != null;
    }

    public boolean isTokenExpired(String token) {
        Jws<Claims> claims = validateToken(token);
        if (claims == null) {
            return false;
        }
        return claims.getPayload().getExpiration().before(new Date());
    }

    public String getSubject(String token) {
        return (String)validateToken(token).getPayload().getSubject();
    }

    public String getRole(String token) {
        return (String)validateToken(token).getPayload().get("role");
    }
}
